name: build
version: 0.1.0
description: A build system for Dart.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build

environment:
  sdk: '>=1.9.1 <2.0.0'

dependencies:
  barback: ^0.15.0
  glob: ^1.1.0
  path: ^1.1.0
  stack_trace: ^1.6.0
  yaml: ^2.1.0

dev_dependencies:
  test: ^0.12.0
  transformer_test: ^0.1.0
