name: build_compilers
version: 0.2.0
description: Builder implementations wrapping Dart compilers.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build

environment:
  sdk: '>=1.22.1 <2.0.0'

dependencies:
