# Created with package:mono_repo v6.3.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_00:
    name: "2.18.0-246.0.dev-with-624dd76b6f3af2ea84a0e5acfc5ec02f14b3f666"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: _test_null_safety_pub_upgrade
        name: _test_null_safety; ./dart-sdk/bin/dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: _test_null_safety
        run: ./dart-sdk/bin/dart pub upgrade
      - name: "_test_null_safety;  ./dart-sdk/bin/dart run build_runner test -- -p chrome,vm --test-randomize-ordering-seed=random"
        if: "always() && steps._test_null_safety_pub_upgrade.conclusion == 'success'"
        working-directory: _test_null_safety
        run: "./dart-sdk/bin/dart run build_runner test -- -p chrome,vm --test-randomize-ordering-seed=random"
