# Created with package:mono_repo v6.3.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_00:
    name: "2.18.0-247.0.dev-with-precompiled-dir"
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: _test_null_safety_pub_upgrade
        name: _test_null_safety; ./dart-sdk/bin/dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: _test_null_safety
        run: ./dart-sdk/bin/dart pub upgrade
      - name: "_test_null_safety; compute diffs!"
        if: "always() && steps._test_null_safety_pub_upgrade.conclusion == 'success'"
        working-directory: _test_null_safety
        run: "./dart-sdk/bin/dart run build_runner build test -o build-gh && diff -r ./build ./build-gh && ./dart-sdk/bin/dart run test --precompiled ./build-gh -p chrome"
